spring:
  profiles:
    active: local
  config:
    use-legacy-processing: true
server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/baeldung.p12
    key-store-password: 123456
    key-alias: baeldung
logbook:
  write:
    level: INFO
  obfuscate:
    headers:
      - host
      - origin
      - referer
      - user-agent
      - accept-encoding
  exclude:
    - /health
fido2-server:
  scheme: http
  host: obk-enrollments-api.obk-hml.limbo.work
  port: 80
  endpoint:
    get-reg-challenge: /enrollments/v1/enrollments/{ENROLLMENT_ID}/fido-registration-options
    get-auth-challenge: /enrollments/v1/enrollments/{ENROLLMENT_ID}/fido-sign-options
    send-reg-response: /enrollments/v1/enrollments/{ENROLLMENT_ID}/fido-registration
    send-auth-response: /enrollments/v1/enrollments/{ENROLLMENT_ID}/consents/{CONSENT_ID}/authenticate
    get-delete-credentials: /fido2/credentials

